language: java
install: true
sudo: false

install:
  - bash .travis.install-maven.sh "${MVN_VERSION}" "${HOME}/mvn-home"
  - export M2_HOME=${HOME}/mvn-home
  - export PATH=${HOME}/mvn-home/bin:${PATH}
  - mvn -version

addons:
  apt:
    packages:
      - fluxbox

cache:
 directories:
   - $HOME/.m2/repository

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - fluxbox &> ~/fluxbox.log &
  - sleep 3

matrix:
  include:
    - addons:
        apt:
          packages:
            - fluxbox
            - openjdk-6-jdk
      jdk: openjdk6
      env: MVN_VERSION="3.2.5"
    - jdk: openjdk7
      env: MVN_VERSION="3.3.9"
    - jdk: oraclejdk8
      env: MVN_VERSION="3.3.9"
# FIXME:
# Travis build fail on JDK 9 due to missing JAXB module in classpath
#    - jdk: oraclejdk9
#      env: MVN_VERSION="3.3.9"

env:
  global:
    - JAVA_OPTS="-Djava.awt.headless=false"

script:
  - mvn -U clean verify
  - mvn verify -Pwith-gui-tests

notifications:
  email: false
