dist: trusty
language: java
install: true
sudo: false

env:
  global:
    - JAVA_OPTS="-Djava.awt.headless=false -Dhttps.protocols=TLSv1.2 -Djdk.tls.client.protocols=TLSv1.2"
    - MVN_VERSION="3.6.3"

before_install:
  - cp ./.travis.settings.xml $HOME/.m2/settings.xml
  - bash .travis.install-maven.sh "${MVN_VERSION}" "${HOME}/mvn-home";
  - export M2_HOME=${HOME}/mvn-home;

install:
  - export PATH="$M2_HOME/bin:$JAVA_HOME/bin:$PATH"
  - mvn -version

addons:
  apt:
    packages:
      - fluxbox

cache:
 directories:
   - $HOME/.m2/repository
   
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - fluxbox &> ~/fluxbox.log &
  - sleep 3

matrix:
  - jdk: openjdk8
# FIXME:
# Travis build fail on JDK 11 due to missing JAXB module in classpath
#    - jdk: oraclejdk11

script:
  - mvn -U clean verify
  - mvn verify -Pwith-gui-tests

notifications:
  email: false
