name: Build IzPack Project

on:
  push:
    branches:
      - main
      - other-branch # Add the specific branches you want to monitor

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Build with Maven
        run: |
          echo "Running Maven clean package"
          mvn -f pom.xml clean package -X > build.log 2>&1
          cat build.log
          echo "Maven command completed"

      - name: List directory structure
        run: |
          echo "Listing root directory:"
          ls -la
          echo "Listing installer target directory:"
          ls -la installer/target || echo "Installer target directory does not exist."

      - name: Upload Build Log
        uses: actions/upload-artifact@v4
        with:
          name: build-log
          path: build.log

      - name: Upload Installer Artifact
        uses: actions/upload-artifact@v4
        with:
          name: izpack-installer
          path: installer/target/*.jar
          if-no-files-found: error
