name: Build IzPack

on:
  push:
    branches:
      - 5.1
      
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Build with Maven
        run: mvn clean install
        env:
          ACTIONS_STEP_DEBUG: true

      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: IzPack
          path: target/
